apiVersion: v1
kind: SecretSchema
metadata:
  name: app-secret-schema
spec:
  required:
    - DB_USERNAME
    - DB_PASSWORD
    - REGISTRY_PULL_SECRET
    - TLS_SECRET_REF
  source: external-secret-store
